name: 'train'
device: 'cuda:0'
seed: 42
output_dir: ./work_dirs
num_workers: 2
frozen_weights: null
resume: null

data:
  data_root: ./data/change
  transform: True
  resizing: False
  patch: False
  flip: False

model:
  num_classes: 1
  backbone_name: "swin_base_patch4_window7_224"
  bev_name: "LinearAttention"  # [LinearAttention, Transformer]
  diff_attention: "CBAM"  # ['SE', 'CBAM']
  out_dims: [256, 256, 256, 256]
  use_token_connector: False  # 是否降低 token 维度
  pretrained: True
  img_size: 512
  use_text_description: True  # 是否使用文本描述
  text_encoder_name: "bert-base-uncased"  # [microsoft/phi-1_5, bert-base-uncased]
  freeze_text_encoder: True # 冻结模型参数

loss:
  weight_ce: 1.2  # 分类损失函数
  weight_dice: 1.0  # 预测与真实标签之间的重叠度
  weight_focal: 1.0  # 用于解决分类问题中的类别不平衡问题
  alpha: 0.5  # 平衡正负样本的比例。
  gamma: 3.0  # 聚焦参数，控制简单样本的下降速率。
  weight_bcl: 0.2  # 衡量正负样本对之间的差异

logger:
  log_name: 'Seg_log'
  level: 'INFO'

training:
  start_epoch: 1
  epochs: 200
  lr: 0.0001
  lr_backbone: 0.00001
  lr_drop: 200
  batch_size: 2
  eval_freq: 1
  start_eval: 1

test:
  batch_size: 1
  weight_path: "./work_dirs/best_f1.pth"