name: 'train'
device: 'cuda:1'
seed: 42
output_dir: ./work_dirs
num_workers: 2
frozen_weights: null
resume: null
data_root: ./data/change

data:
  transform: true
  color_jitter: 0
  rotation_degree: 0
  gamma_range: [1.0, 1.0]
  affine_degree: 0
  erase_prob: 0
  erase_ratio: [0, 0]
  blur_sigma: 0

model:
  num_classes: 1
  backbone_name: "swin_base_patch4_window7_224"
  bev_name: "LinearAttention"  # [LinearAttention, Transformer]
  diff_attention: "CBAM"  # ['SE', 'CBAM']
  out_dims: [256, 256, 256, 256]
  use_token_connector: False  # 是否降低 token 维度
  pretrained: True
  img_size: 512
  use_text_description: True  # 是否使用文本描述
  text_encoder_name: "bert-base-uncased"  # [microsoft/phi-1_5, bert-base-uncased]
  freeze_text_encoder: True # 冻结模型参数

loss:
  weight_ce: 1.0  # 分类任务基础损失
  weight_dice: 1.5  # 提升边界分割精度
  weight_focal: 1.5  # 缓解类别不平衡
  alpha: 0.6  # 平衡正负样本的比例
  gamma: 2.0  # 聚焦参数，控制简单样本的下降速率
  weight_bcl: 0.3  # 增强特征区分度

logger:
  log_name: 'Seg_log'
  level: 'INFO'

training:
  start_epoch: 1
  epochs: 200
  scheduler: 'step'  # [step, plateau]
  lr: 0.0001
  lr_backbone: 0.00001
  lr_drop: 200
  batch_size: 2
  eval_freq: 1
  start_eval: 1

test:
  test_img_dirs: './data/change/val'
  batch_size: 1
  device: 'cuda:1'
  save_dir: "./work_dirs"
  name: "test"
  weight_path: "./work_dirs/train_1/checkpoints/best_iou.pth"
  show: True
  show_overlay: False