name: 'train'
device: 'cuda:0'
seed: 42
output_dir: ./work_dirs
num_workers: 12
resume: null  # 如果存在，则恢复训练
prompt: 'Buildings with changes, Mound changes.'
onnx_weights: './examples/ONNXRuntime/weights'

data:
  data_root: './data/change'
  data_format: 'custom'                           # [default, custom]
  transforms:
    apply_prob: 0.5                               # 应用概率
    color_jitter: 0.2                             # 颜色抖动
    rotation_degree: 15                           # 旋转角度
    gamma_range: [0.8, 1.2]                       # Gamma矫正
    affine_degree: 0                              # 仿射变换
    erase_prob: 0                                 # 随机擦除
    erase_ratio: [0, 0]                           # 随机擦除大小
    blur_sigma: 0.3                               # 高斯模糊
    clahe: 0.5                                    # 直方图均衡化

model:
  num_classes: 1
  backbone_name: "swin_base_patch4_window7_224"   # ['swin_base_patch4_window7_224', 'resnet50', 'hgnetv2']
  bev_name: "LinearAttention"                     # [LinearAttention, Transformer]
  fpn_type: "L-FPN"                               # ['FPN', 'L-FPN']
  use_ega: true                                   # 是否使用 边缘-高斯聚合（EGA）模块
  diff_attention: "CBAM"                          # ['SE', 'CBAM']
  out_dims: [256, 256, 256, 256]
  use_token_connector: False                      # 是否降低 token 维度
  pretrained: True                                # 是否使用预训练的模型参数
  img_size: 512
  text_encoder_name: "bert-base-uncased"          # [microsoft/phi-1_5, bert-base-uncased]
  desc_embs: null                                 # 文本描述向量地址 "./weights/embeddings.pt"
  freeze_text_encoder: True                       # 冻结模型参数

loss:
  weight_ce: 1.0                                  # 分类任务基础损失
  weight_dice: 1.5                                # 提升边界分割精度
  weight_focal: 1.5                               # 缓解类别不平衡
  alpha: 0.6                                      # 平衡正负样本的比例
  gamma: 2.0                                      # 聚焦参数，控制简单样本的下降速率
  weight_bcl: 0.3                                 # 增强特征区分度

logger:
  log_name: 'Seg_log'
  level: 'INFO'

training:
  start_epoch: 1
  epochs: 200
  scheduler: 'step'  # [step, plateau]
  lr: 0.0001
  lr_backbone: 0.00001
  lr_drop: 20
  weight_decay: 0.0001
  batch_size: 4
  eval_freq: 1
  start_eval: 1
  threshold: 0.5

test:
  img_dirs: './data/change'
  batch_size: 1
  threshold: 0.5
  device: 'cuda:1'
  save_dir: "./work_dirs"
  name: "test"
  weights_dir: './work_dirs/train/checkpoints/best_iou.pth'
  show: True
  show_overlay: False

infer:
  name: 'BL2_5'
  input_dir: '/data/BL2_5'
  chunk_size: 0  # 25600
  weights_dir: './work_dirs/train/checkpoints/best_iou.pth'
  output_dir: './outputs'
  threshold: 0.5
  device: 'cuda:1'
